version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: art-guard-db
    environment:
      POSTGRES_USER: artguard
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: art-guard-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: